#!/bin/sh

ln -sf ~/dotfiles/.gitconfig ~/.gitconfig
ln -sf ~/dotfiles/.gitignore_global ~/.gitignore_global

mkdir -p ~/.vim/bundle
# git clone git://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim
ln -sf ~/dotfiles/.zshrc ~/.zshrc
ln -sf ~/dotfiles/.zshrc.alias ~/.zshrc.alias
ln -sf ~/dotfiles/.vimrc ~/.vimrc
ln -sf ~/dotfiles/.tmux.conf ~/.tmux.conf

mkdir -p ~/.config/karabiner/
mkdir -p ~/.config/karabiner/assets/complex_modifications/
ln -sf ~/dotfiles/karabiner.json ~/.config/karabiner/karabiner.json
ln -sf ~/dotfiles/karabiner/assets/complex_modifications/1.json ~/.config/karabiner/assets/complex_modifications/1.json

ln -sf ~/dotfiles/.vimrc.set ~/.vim/.vimrc.set
ln -sf ~/dotfiles/.vimrc.keymap ~/.vim/.vimrc.keymap
ln -sf ~/dotfiles/.vimrc.plugins ~/.vim/.vimrc.plugins
ln -sf ~/dotfiles/.vimrc.script ~/.vim/.vimrc.script
ln -sf ~/dotfiles/.vimrc.dein ~/.vim/.vimrc.dein


mkdir -p $HOME/.vim/rc
ln -sf ~/dotfiles/vim/rc/dein.toml ~/.vim/rc/dein.toml
ln -sf ~/dotfiles/vim/rc/dein_lazy.toml ~/.vim/rc/dein_lazy.toml

mkdir -p ~/local
ln -sf ~/dotfiles/local/script ~/local/


# latexmkrc
ln -sf ~/dotfiles/.latexmkrc ~/.latexmkrc

# RubyMine
ln -sf ~/dotfiles/.ideavimrc ~/.ideavimrc

# tig
ln -sf ~/dotfiles/.tigrc ~/.tigrc

# peco
ln -sf ~/dotfiles/peco ~/.config/peco

# tmuxinator
gem install tmuxinator
ln -sf ~/dotfiles/tmuxinator ~/.config/tmuxinator

# rubocop.yml
gem install rubocop
ln -sf ~/dotfiles/.rubocop.yml ~/.rubocop.yml

# docker compose
# https://docs.docker.com/compose/completion/#bash
# mkdir -p ~/.zsh/completion
# curl -L https://raw.githubusercontent.com/docker/compose/1.17.0/contrib/completion/zsh/_docker-compose > ~/.zsh/completion/_docker-compose

mkdir -p $HOME/.zsh
git clone git://github.com/zsh-users/zsh-syntax-highlighting.git ~/.zsh/zsh-syntax-highlighting


# home brew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install readline
brew install jq
brew install gradle
brew install python3
brew install peco
brew install redis
brew install mysql
brew install cmake
brew install ghq
brew install automake
brew install selenium-server-standalone
brew cask install chromedriver
brew install imagemagick
brew install graphviz
