#!/bin/sh

sudo yum -y install ncurses-devel


wget http://sourceforge.net/projects/levent/files/latest/download
# 今回はなぜかdownloadという名前で落ちてきました。
tar -xvf download
cd libevent-2.0.22-stable/
./configure && make
sudo make install

sudo echo "/usr/local/lib" > /etc/ld.so.conf.d/libevent.conf
sudo ldconfig

ln -s /usr/local/lib/libevent-2.0.so.5 /usr/lib64/libevent-2.0.so.5


wget https://github.com/tmux/tmux/releases/download/2.0/tmux-2.0.tar.gz
tar -xvf tmux-2.0.tar.gz
cd tmux-2.0
./configure && make
sudo make install
