#!/bin/sh

# OS X El Capitan v10.11.5
# brew install ghc
# brew install cabal-install
# cabal update
# brew install haskell-platform
# cabal install language-c

brew install stack
stack setup
stack install ghc-mod hspec hlint
