#!/Users/meriy100/.rbenv/shims/ruby
shresult = `pmset -g ps`
s = shresult.match /Now drawing from '(?<from>\w+ \w+)'/
status = s[:from] == "AC Power" ? "⚡︎" : "❚"
shresult.match /(\d+)%;/ do |m|
  case m[1]
  when "0"..."30"
    print "#[fg=colour196]"
  when "30"..."60"
    print "#[fg=colour220]"
  when "60"..."100"
    print "#[fg=colour46]"
  when "100"
    print "#[fg=colour33]"
  end
  print (status * (m[1].to_i / 20 + 1)).rjust(6)
  print "#{m[1]}%"
  print "#[default]"
end

